//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingVLU.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    public partial class item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public item()
        {
            this.comments = new HashSet<comment>();
            this.order_detail = new HashSet<order_detail>();
        }
        public HttpPostedFileBase avatar { get; set; }
        public HttpPostedFileBase pic01 { get; set; }
        public HttpPostedFileBase pic02 { get; set; }
        public HttpPostedFileBase pic03 { get; set; }
        public HttpPostedFileBase pic04 { get; set; }
        public HttpPostedFileBase pic05 { get; set; }

        public int id { get; set; }
        public string item_name { get; set; }
        public string description { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> status { get; set; }
        public string phone_contact { get; set; }
        public int seller_id { get; set; }
        public Nullable<int> buyer_id { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string index_image { get; set; }
        public string detail_image1 { get; set; }
        public string detail_image2 { get; set; }
        public string detail_image3 { get; set; }
        public string detail_image4 { get; set; }
        public string detail_image5 { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> approve { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments { get; set; }
        public virtual item_status item_status { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_detail> order_detail { get; set; }

    }
}
