//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingVLU.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vlutrading3545Entities : DbContext
    {
        public vlutrading3545Entities()
            : base("name=vlutrading3545Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<order_detail> order_detail { get; set; }
        public virtual DbSet<tempshoppingcart> tempshoppingcarts { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<item_status> item_status { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<security_question> security_question { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_personal_information> user_personal_information { get; set; }
    }
}
