//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingVLU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_items
    {
        public int id { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<int> buyer_id { get; set; }
        public string ship_name { get; set; }
        public string ship_mobile { get; set; }
        public string ship_address { get; set; }
        public string ship_email { get; set; }
        public Nullable<int> status { get; set; }
    }
}
