//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradingVLU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int item_id { get; set; }
        public int user_id { get; set; }
        public int status { get; set; }
        public string username { get; set; }
        public string item_name { get; set; }
    
        public virtual item item { get; set; }
        public virtual user user { get; set; }
    }
}
